version: '3'

services:
  thingsboard:
    restart: unless-stopped
    image: thingsboard/tb-postgres
    environment:
      - TB_QUEUE_TYPE=in-memory
      - TZ=Europe/Amsterdam
      - MQTT_SSL_ENABLED=true
      - MQTT_SSL_CREDENTIALS_TYPE=PEM
      - MQTT_SSL_PEM_CERT=/certs/server.pem
      - MQTT_SSL_PEM_KEY=/certs/server_key.pem
      - MQTT_SSL_SKIP_VALIDITY_CHECK_FOR_CLIENT_CERT=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/thingsboard
      - SPRING_DATASOURCE_USERNAME=thingsboard
      - SPRING_DATASOURCE_PASSWORD=
    volumes:
      - type: bind
        source: ./thingsboard/data
        target: /data
      - type: bind
        source: ./thingsboard/logs
        target: /var/log/thingsboard
      - type: bind
        source: ./thingsboard/certs
        target: /certs
    ports:
      - 1883:1883
      - 8883:8883
      - 7070:7070
      - 5683-5688:5683-5688/udp
    networks:
      thingsboard_nw:

  postgresql:
    restart: unless-stopped
    image: postgres:12-alpine
    user: 1000:1000
    environment:
      - TZ=Europe/Amsterdam
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=thingsboard
    volumes:
      - type: bind
        source: ./postgresql
        target: /var/lib/postgresql/data
      - type: bind
        source: /etc/passwd
        target: /etc/passwd
        read_only: true
    ports:
      - 5432:5432
    networks:
      thingsboard_nw:

  nginx:
    restart: unless-stopped
    image: lscr.io/linuxserver/swag
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1000
      - PGID=1000
      - URL=ddss-sensebox.nl
      - SUBDOMAINS=test,mail
      - VALIDATION=http
      - ONLY_SUBDOMAINS=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: ./nginx
        target: /config
    networks:
      thingsboard_nw:

  poste:
    restart: unless-stopped
    image: analogic/poste.io
    ports:
      - 25:25
      - 110:110
      - 143:143
      - 465:465
      - 587:587
      - 993:993
      - 995:995
      - 4190:4190
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - HTTPS=OFF
      - DISABLE_CLAMAV=TRUE
    volumes:
      - type: bind
        source: ./poste
        target: /data
    networks:
      thingsboard_nw:

networks:
  thingsboard_nw:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
